spring.datasource.url=jdbc:postgresql://localhost:5432/falcao_sombrio
spring.datasource.username=falcao
spring.datasource.password=falcao2026
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
server.port=8080
